# Default values for tibber-pulse-reader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config: {}

image:
  repository: ghcr.io/micw/homedatabroker
  pullPolicy: Always
  tag: master

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

#resources:
  # limits:
  #   cpu: 100m
  #   memory: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
