# derived from https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
name: Create and publish Docker image
on:
  push:
    branches:
    - feature/*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/homedatabroker

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run maven tests
        run: mvn -Duser.timezone=Europe/Berlin --batch-mode --update-snapshots verify
