apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homedatabroker.fullname" . }}-config
  labels:
    {{- include "homedatabroker.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | required "config is required" | toYaml | nindent 4 }}
